//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace System.Globalization
{
	public enum Culture
	{
		Default=127,
		/// <summary>
		/// Afrikaans
		/// </summary>
		AF = 54,
		/// <summary>
		/// Amharic
		/// </summary>
		AM = 94,
		/// <summary>
		/// Arabic
		/// </summary>
		AR = 1,
		/// <summary>
		/// Mapudungun
		/// </summary>
		ARN = 122,
		/// <summary>
		/// Assamese
		/// </summary>
		AS = 77,
		/// <summary>
		/// Azerbaijani
		/// </summary>
		AZ = 44,
		/// <summary>
		/// Azerbaijani (Cyrillic)
		/// </summary>
		AZ_CYRL = 29740,
		/// <summary>
		/// Azerbaijani (Latin)
		/// </summary>
		AZ_LATN = 30764,
		/// <summary>
		/// Bashkir
		/// </summary>
		BA = 109,
		/// <summary>
		/// Belarusian
		/// </summary>
		BE = 35,
		/// <summary>
		/// Bulgarian
		/// </summary>
		BG = 2,
		/// <summary>
		/// Bangla
		/// </summary>
		BN = 69,
		/// <summary>
		/// Tibetan
		/// </summary>
		BO = 81,
		/// <summary>
		/// Breton
		/// </summary>
		BR = 126,
		/// <summary>
		/// Bosnian
		/// </summary>
		BS = 30746,
		/// <summary>
		/// Bosnian (Cyrillic)
		/// </summary>
		BS_CYRL = 25626,
		/// <summary>
		/// Bosnian (Latin)
		/// </summary>
		BS_LATN = 26650,
		/// <summary>
		/// Catalan
		/// </summary>
		CA = 3,
		/// <summary>
		/// Cherokee
		/// </summary>
		CHR = 92,
		/// <summary>
		/// Cherokee (Cherokee)
		/// </summary>
		CHR_CHER = 31836,
		/// <summary>
		/// Corsican
		/// </summary>
		CO = 131,
		/// <summary>
		/// Czech
		/// </summary>
		CS = 5,
		/// <summary>
		/// Welsh
		/// </summary>
		CY = 82,
		/// <summary>
		/// Danish
		/// </summary>
		DA = 6,
		/// <summary>
		/// German
		/// </summary>
		DE = 7,
		/// <summary>
		/// Lower Sorbian
		/// </summary>
		DSB = 31790,
		/// <summary>
		/// Divehi
		/// </summary>
		DV = 101,
		/// <summary>
		/// Greek
		/// </summary>
		EL = 8,
		/// <summary>
		/// English
		/// </summary>
		EN = 9,
		/// <summary>
		/// Spanish
		/// </summary>
		ES = 10,
		/// <summary>
		/// Estonian
		/// </summary>
		ET = 37,
		/// <summary>
		/// Basque
		/// </summary>
		EU = 45,
		/// <summary>
		/// Persian
		/// </summary>
		FA = 41,
		/// <summary>
		/// Fulah
		/// </summary>
		FF = 103,
		/// <summary>
		/// Fulah (Latin)
		/// </summary>
		FF_LATN = 31847,
		/// <summary>
		/// Finnish
		/// </summary>
		FI = 11,
		/// <summary>
		/// Filipino
		/// </summary>
		FIL = 100,
		/// <summary>
		/// Faroese
		/// </summary>
		FO = 56,
		/// <summary>
		/// French
		/// </summary>
		FR = 12,
		/// <summary>
		/// Frisian
		/// </summary>
		FY = 98,
		/// <summary>
		/// Irish
		/// </summary>
		GA = 60,
		/// <summary>
		/// Scottish Gaelic
		/// </summary>
		GD = 145,
		/// <summary>
		/// Galician
		/// </summary>
		GL = 86,
		/// <summary>
		/// Guarani
		/// </summary>
		GN = 116,
		/// <summary>
		/// Alsatian
		/// </summary>
		GSW = 132,
		/// <summary>
		/// Gujarati
		/// </summary>
		GU = 71,
		/// <summary>
		/// Hausa
		/// </summary>
		HA = 104,
		/// <summary>
		/// Hausa (Latin)
		/// </summary>
		HA_LATN = 31848,
		/// <summary>
		/// Hawaiian
		/// </summary>
		HAW = 117,
		/// <summary>
		/// Hebrew
		/// </summary>
		HE = 13,
		/// <summary>
		/// Hindi
		/// </summary>
		HI = 57,
		/// <summary>
		/// Croatian
		/// </summary>
		HR = 26,
		/// <summary>
		/// Upper Sorbian
		/// </summary>
		HSB = 46,
		/// <summary>
		/// Hungarian
		/// </summary>
		HU = 14,
		/// <summary>
		/// Armenian
		/// </summary>
		HY = 43,
		/// <summary>
		/// Indonesian
		/// </summary>
		ID = 33,
		/// <summary>
		/// Igbo
		/// </summary>
		IG = 112,
		/// <summary>
		/// Yi
		/// </summary>
		II = 120,
		/// <summary>
		/// Icelandic
		/// </summary>
		IS = 15,
		/// <summary>
		/// Italian
		/// </summary>
		IT = 16,
		/// <summary>
		/// Inuktitut
		/// </summary>
		IU = 93,
		/// <summary>
		/// Inuktitut (Syllabics)
		/// </summary>
		IU_CANS = 30813,
		/// <summary>
		/// Inuktitut (Latin)
		/// </summary>
		IU_LATN = 31837,
		/// <summary>
		/// Japanese
		/// </summary>
		JA = 17,
		/// <summary>
		/// Basa Jawa
		/// </summary>
		JV = 4096,
		/// <summary>
		/// Georgian
		/// </summary>
		KA = 55,
		/// <summary>
		/// Kazakh
		/// </summary>
		KK = 63,
		/// <summary>
		/// Greenlandic
		/// </summary>
		KL = 111,
		/// <summary>
		/// Khmer
		/// </summary>
		KM = 83,
		/// <summary>
		/// Kannada
		/// </summary>
		KN = 75,
		/// <summary>
		/// Korean
		/// </summary>
		KO = 18,
		/// <summary>
		/// Konkani
		/// </summary>
		KOK = 87,
		/// <summary>
		/// Central Kurdish
		/// </summary>
		KU = 146,
		/// <summary>
		/// Central Kurdish (Arabic)
		/// </summary>
		KU_ARAB = 31890,
		/// <summary>
		/// Kyrgyz
		/// </summary>
		KY = 64,
		/// <summary>
		/// Luxembourgish
		/// </summary>
		LB = 110,
		/// <summary>
		/// Lao
		/// </summary>
		LO = 84,
		/// <summary>
		/// Lithuanian
		/// </summary>
		LT = 39,
		/// <summary>
		/// Latvian
		/// </summary>
		LV = 38,
		/// <summary>
		/// Maori
		/// </summary>
		MI = 129,
		/// <summary>
		/// Macedonian (FYROM)
		/// </summary>
		MK = 47,
		/// <summary>
		/// Malayalam
		/// </summary>
		ML = 76,
		/// <summary>
		/// Mongolian
		/// </summary>
		MN = 80,
		/// <summary>
		/// Mongolian (Cyrillic)
		/// </summary>
		MN_CYRL = 30800,
		/// <summary>
		/// Mongolian (Traditional Mongolian)
		/// </summary>
		MN_MONG = 31824,
		/// <summary>
		/// Mohawk
		/// </summary>
		MOH = 124,
		/// <summary>
		/// Marathi
		/// </summary>
		MR = 78,
		/// <summary>
		/// Malay
		/// </summary>
		MS = 62,
		/// <summary>
		/// Maltese
		/// </summary>
		MT = 58,
		/// <summary>
		/// Burmese
		/// </summary>
		MY = 85,
		/// <summary>
		/// Norwegian (Bokmål)
		/// </summary>
		NB = 31764,
		/// <summary>
		/// Nepali
		/// </summary>
		NE = 97,
		/// <summary>
		/// Dutch
		/// </summary>
		NL = 19,
		/// <summary>
		/// Norwegian (Nynorsk)
		/// </summary>
		NN = 30740,
		/// <summary>
		/// Norwegian
		/// </summary>
		NO = 20,
		/// <summary>
		/// Sesotho sa Leboa
		/// </summary>
		NSO = 108,
		/// <summary>
		/// Occitan
		/// </summary>
		OC = 130,
		/// <summary>
		/// Oromo
		/// </summary>
		OM = 114,
		/// <summary>
		/// Odia
		/// </summary>
		OR = 72,
		/// <summary>
		/// Punjabi
		/// </summary>
		PA = 70,
		/// <summary>
		/// Punjabi (Arabic)
		/// </summary>
		PA_ARAB = 31814,
		/// <summary>
		/// Polish
		/// </summary>
		PL = 21,
		/// <summary>
		/// Dari
		/// </summary>
		PRS = 140,
		/// <summary>
		/// Pashto
		/// </summary>
		PS = 99,
		/// <summary>
		/// Portuguese
		/// </summary>
		PT = 22,
		/// <summary>
		/// K'iche
		/// </summary>
		QUT = 134,
		/// <summary>
		/// Quechua
		/// </summary>
		QUZ = 107,
		/// <summary>
		/// Romansh
		/// </summary>
		RM = 23,
		/// <summary>
		/// Romanian
		/// </summary>
		RO = 24,
		/// <summary>
		/// Russian
		/// </summary>
		RU = 25,
		/// <summary>
		/// Kinyarwanda
		/// </summary>
		RW = 135,
		/// <summary>
		/// Sanskrit
		/// </summary>
		SA = 79,
		/// <summary>
		/// Sakha
		/// </summary>
		SAH = 133,
		/// <summary>
		/// Sindhi
		/// </summary>
		SD = 89,
		/// <summary>
		/// Sindhi (Arabic)
		/// </summary>
		SD_ARAB = 31833,
		/// <summary>
		/// Sami (Northern)
		/// </summary>
		SE = 59,
		/// <summary>
		/// Sinhala
		/// </summary>
		SI = 91,
		/// <summary>
		/// Slovak
		/// </summary>
		SK = 27,
		/// <summary>
		/// Slovenian
		/// </summary>
		SL = 36,
		/// <summary>
		/// Sami (Southern)
		/// </summary>
		SMA = 30779,
		/// <summary>
		/// Sami (Lule)
		/// </summary>
		SMJ = 31803,
		/// <summary>
		/// Sami (Inari)
		/// </summary>
		SMN = 28731,
		/// <summary>
		/// Sami (Skolt)
		/// </summary>
		SMS = 29755,
		/// <summary>
		/// Somali
		/// </summary>
		SO = 119,
		/// <summary>
		/// Albanian
		/// </summary>
		SQ = 28,
		/// <summary>
		/// Serbian
		/// </summary>
		SR = 31770,
		/// <summary>
		/// Serbian (Cyrillic)
		/// </summary>
		SR_CYRL = 27674,
		/// <summary>
		/// Serbian (Latin)
		/// </summary>
		SR_LATN = 28698,
		/// <summary>
		/// Southern Sotho
		/// </summary>
		ST = 48,
		/// <summary>
		/// Swedish
		/// </summary>
		SV = 29,
		/// <summary>
		/// Kiswahili
		/// </summary>
		SW = 65,
		/// <summary>
		/// Syriac
		/// </summary>
		SYR = 90,
		/// <summary>
		/// Tamil
		/// </summary>
		TA = 73,
		/// <summary>
		/// Telugu
		/// </summary>
		TE = 74,
		/// <summary>
		/// Tajik
		/// </summary>
		TG = 40,
		/// <summary>
		/// Tajik (Cyrillic)
		/// </summary>
		TG_CYRL = 31784,
		/// <summary>
		/// Thai
		/// </summary>
		TH = 30,
		/// <summary>
		/// Tigrinya
		/// </summary>
		TI = 115,
		/// <summary>
		/// Turkmen
		/// </summary>
		TK = 66,
		/// <summary>
		/// Setswana
		/// </summary>
		TN = 50,
		/// <summary>
		/// Turkish
		/// </summary>
		TR = 31,
		/// <summary>
		/// Tsonga
		/// </summary>
		TS = 49,
		/// <summary>
		/// Tatar
		/// </summary>
		TT = 68,
		/// <summary>
		/// Tamazight
		/// </summary>
		TZM = 95,
		/// <summary>
		/// Tamazight (Latin)
		/// </summary>
		TZM_LATN = 31839,
		/// <summary>
		/// Tamazight (Tifinagh)
		/// </summary>
		TZM_TFNG = 30815,
		/// <summary>
		/// Uyghur
		/// </summary>
		UG = 128,
		/// <summary>
		/// Ukrainian
		/// </summary>
		UK = 34,
		/// <summary>
		/// Urdu
		/// </summary>
		UR = 32,
		/// <summary>
		/// Uzbek
		/// </summary>
		UZ = 67,
		/// <summary>
		/// Uzbek (Cyrillic)
		/// </summary>
		UZ_CYRL = 30787,
		/// <summary>
		/// Uzbek (Latin)
		/// </summary>
		UZ_LATN = 31811,
		/// <summary>
		/// Vietnamese
		/// </summary>
		VI = 42,
		/// <summary>
		/// Wolof
		/// </summary>
		WO = 136,
		/// <summary>
		/// isiXhosa
		/// </summary>
		XH = 52,
		/// <summary>
		/// Yoruba
		/// </summary>
		YO = 106,
		/// <summary>
		/// Chinese
		/// </summary>
		ZH = 30724,
		/// <summary>
		/// Chinese (Simplified) Legacy
		/// </summary>
		ZH_CHS = 4,
		/// <summary>
		/// Chinese (Traditional) Legacy
		/// </summary>
		ZH_CHT = 31748,
		/// <summary>
		/// isiZulu
		/// </summary>
		ZU = 53
	}
	public enum SpecificCulture
	{
		Default=127,
		/// <summary>
		/// Afrikaans
		/// </summary>
		AF = 54,
		/// <summary>
		/// Afrikaans (South Africa)
		/// </summary>
		AF_ZA = 1078,
		/// <summary>
		/// Amharic
		/// </summary>
		AM = 94,
		/// <summary>
		/// Amharic (Ethiopia)
		/// </summary>
		AM_ET = 1118,
		/// <summary>
		/// Arabic
		/// </summary>
		AR = 1,
		/// <summary>
		/// Arabic (U.A.E.)
		/// </summary>
		AR_AE = 14337,
		/// <summary>
		/// Arabic (Bahrain)
		/// </summary>
		AR_BH = 15361,
		/// <summary>
		/// Arabic (Algeria)
		/// </summary>
		AR_DZ = 5121,
		/// <summary>
		/// Arabic (Egypt)
		/// </summary>
		AR_EG = 3073,
		/// <summary>
		/// Arabic (Iraq)
		/// </summary>
		AR_IQ = 2049,
		/// <summary>
		/// Arabic (Jordan)
		/// </summary>
		AR_JO = 11265,
		/// <summary>
		/// Arabic (Kuwait)
		/// </summary>
		AR_KW = 13313,
		/// <summary>
		/// Arabic (Lebanon)
		/// </summary>
		AR_LB = 12289,
		/// <summary>
		/// Arabic (Libya)
		/// </summary>
		AR_LY = 4097,
		/// <summary>
		/// Arabic (Morocco)
		/// </summary>
		AR_MA = 6145,
		/// <summary>
		/// Arabic (Oman)
		/// </summary>
		AR_OM = 8193,
		/// <summary>
		/// Arabic (Qatar)
		/// </summary>
		AR_QA = 16385,
		/// <summary>
		/// Arabic (Saudi Arabia)
		/// </summary>
		AR_SA = 1025,
		/// <summary>
		/// Arabic (Syria)
		/// </summary>
		AR_SY = 10241,
		/// <summary>
		/// Arabic (Tunisia)
		/// </summary>
		AR_TN = 7169,
		/// <summary>
		/// Arabic (Yemen)
		/// </summary>
		AR_YE = 9217,
		/// <summary>
		/// Mapudungun
		/// </summary>
		ARN = 122,
		/// <summary>
		/// Mapudungun (Chile)
		/// </summary>
		ARN_CL = 1146,
		/// <summary>
		/// Assamese
		/// </summary>
		AS = 77,
		/// <summary>
		/// Assamese (India)
		/// </summary>
		AS_IN = 1101,
		/// <summary>
		/// Azerbaijani
		/// </summary>
		AZ = 44,
		/// <summary>
		/// Azerbaijani (Cyrillic)
		/// </summary>
		AZ_CYRL = 29740,
		/// <summary>
		/// Azerbaijani (Cyrillic, Azerbaijan)
		/// </summary>
		AZ_CYRL_AZ = 2092,
		/// <summary>
		/// Azerbaijani (Latin)
		/// </summary>
		AZ_LATN = 30764,
		/// <summary>
		/// Azerbaijani (Latin, Azerbaijan)
		/// </summary>
		AZ_LATN_AZ = 1068,
		/// <summary>
		/// Bashkir
		/// </summary>
		BA = 109,
		/// <summary>
		/// Bashkir (Russia)
		/// </summary>
		BA_RU = 1133,
		/// <summary>
		/// Belarusian
		/// </summary>
		BE = 35,
		/// <summary>
		/// Belarusian (Belarus)
		/// </summary>
		BE_BY = 1059,
		/// <summary>
		/// Bulgarian
		/// </summary>
		BG = 2,
		/// <summary>
		/// Bulgarian (Bulgaria)
		/// </summary>
		BG_BG = 1026,
		/// <summary>
		/// Bangla
		/// </summary>
		BN = 69,
		/// <summary>
		/// Bangla (Bangladesh)
		/// </summary>
		BN_BD = 2117,
		/// <summary>
		/// Bangla (India)
		/// </summary>
		BN_IN = 1093,
		/// <summary>
		/// Tibetan
		/// </summary>
		BO = 81,
		/// <summary>
		/// Tibetan (PRC)
		/// </summary>
		BO_CN = 1105,
		/// <summary>
		/// Breton
		/// </summary>
		BR = 126,
		/// <summary>
		/// Breton (France)
		/// </summary>
		BR_FR = 1150,
		/// <summary>
		/// Bosnian
		/// </summary>
		BS = 30746,
		/// <summary>
		/// Bosnian (Cyrillic)
		/// </summary>
		BS_CYRL = 25626,
		/// <summary>
		/// Bosnian (Cyrillic, Bosnia and Herzegovina)
		/// </summary>
		BS_CYRL_BA = 8218,
		/// <summary>
		/// Bosnian (Latin)
		/// </summary>
		BS_LATN = 26650,
		/// <summary>
		/// Bosnian (Latin, Bosnia and Herzegovina)
		/// </summary>
		BS_LATN_BA = 5146,
		/// <summary>
		/// Catalan
		/// </summary>
		CA = 3,
		/// <summary>
		/// Catalan (Catalan)
		/// </summary>
		CA_ES = 1027,
		/// <summary>
		/// Valencian (Spain)
		/// </summary>
		CA_ES_VALENCIA = 2051,
		/// <summary>
		/// Cherokee
		/// </summary>
		CHR = 92,
		/// <summary>
		/// Cherokee (Cherokee)
		/// </summary>
		CHR_CHER = 31836,
		/// <summary>
		/// Cherokee (Cherokee)
		/// </summary>
		CHR_CHER_US = 1116,
		/// <summary>
		/// Corsican
		/// </summary>
		CO = 131,
		/// <summary>
		/// Corsican (France)
		/// </summary>
		CO_FR = 1155,
		/// <summary>
		/// Czech
		/// </summary>
		CS = 5,
		/// <summary>
		/// Czech (Czech Republic)
		/// </summary>
		CS_CZ = 1029,
		/// <summary>
		/// Welsh
		/// </summary>
		CY = 82,
		/// <summary>
		/// Welsh (United Kingdom)
		/// </summary>
		CY_GB = 1106,
		/// <summary>
		/// Danish
		/// </summary>
		DA = 6,
		/// <summary>
		/// Danish (Denmark)
		/// </summary>
		DA_DK = 1030,
		/// <summary>
		/// German
		/// </summary>
		DE = 7,
		/// <summary>
		/// German (Austria)
		/// </summary>
		DE_AT = 3079,
		/// <summary>
		/// German (Switzerland)
		/// </summary>
		DE_CH = 2055,
		/// <summary>
		/// German (Germany)
		/// </summary>
		DE_DE = 1031,
		/// <summary>
		/// German (Liechtenstein)
		/// </summary>
		DE_LI = 5127,
		/// <summary>
		/// German (Luxembourg)
		/// </summary>
		DE_LU = 4103,
		/// <summary>
		/// Lower Sorbian
		/// </summary>
		DSB = 31790,
		/// <summary>
		/// Lower Sorbian (Germany)
		/// </summary>
		DSB_DE = 2094,
		/// <summary>
		/// Divehi
		/// </summary>
		DV = 101,
		/// <summary>
		/// Divehi (Maldives)
		/// </summary>
		DV_MV = 1125,
		/// <summary>
		/// Greek
		/// </summary>
		EL = 8,
		/// <summary>
		/// Greek (Greece)
		/// </summary>
		EL_GR = 1032,
		/// <summary>
		/// English
		/// </summary>
		EN = 9,
		/// <summary>
		/// English (Caribbean)
		/// </summary>
		EN_029 = 9225,
		/// <summary>
		/// English (Australia)
		/// </summary>
		EN_AU = 3081,
		/// <summary>
		/// English (Belize)
		/// </summary>
		EN_BZ = 10249,
		/// <summary>
		/// English (Canada)
		/// </summary>
		EN_CA = 4105,
		/// <summary>
		/// English (United Kingdom)
		/// </summary>
		EN_GB = 2057,
		/// <summary>
		/// English (Hong Kong SAR)
		/// </summary>
		EN_HK = 15369,
		/// <summary>
		/// English (Ireland)
		/// </summary>
		EN_IE = 6153,
		/// <summary>
		/// English (India)
		/// </summary>
		EN_IN = 16393,
		/// <summary>
		/// English (Jamaica)
		/// </summary>
		EN_JM = 8201,
		/// <summary>
		/// English (Malaysia)
		/// </summary>
		EN_MY = 17417,
		/// <summary>
		/// English (New Zealand)
		/// </summary>
		EN_NZ = 5129,
		/// <summary>
		/// English (Republic of the Philippines)
		/// </summary>
		EN_PH = 13321,
		/// <summary>
		/// English (Singapore)
		/// </summary>
		EN_SG = 18441,
		/// <summary>
		/// English (Trinidad and Tobago)
		/// </summary>
		EN_TT = 11273,
		/// <summary>
		/// English (United States)
		/// </summary>
		EN_US = 1033,
		/// <summary>
		/// English (South Africa)
		/// </summary>
		EN_ZA = 7177,
		/// <summary>
		/// English (Zimbabwe)
		/// </summary>
		EN_ZW = 12297,
		/// <summary>
		/// Spanish
		/// </summary>
		ES = 10,
		/// <summary>
		/// Spanish (Latin America)
		/// </summary>
		ES_419 = 22538,
		/// <summary>
		/// Spanish (Argentina)
		/// </summary>
		ES_AR = 11274,
		/// <summary>
		/// Spanish (Bolivia)
		/// </summary>
		ES_BO = 16394,
		/// <summary>
		/// Spanish (Chile)
		/// </summary>
		ES_CL = 13322,
		/// <summary>
		/// Spanish (Colombia)
		/// </summary>
		ES_CO = 9226,
		/// <summary>
		/// Spanish (Costa Rica)
		/// </summary>
		ES_CR = 5130,
		/// <summary>
		/// Spanish (Dominican Republic)
		/// </summary>
		ES_DO = 7178,
		/// <summary>
		/// Spanish (Ecuador)
		/// </summary>
		ES_EC = 12298,
		/// <summary>
		/// Spanish (Spain)
		/// </summary>
		ES_ES = 3082,
		/// <summary>
		/// Spanish (Guatemala)
		/// </summary>
		ES_GT = 4106,
		/// <summary>
		/// Spanish (Honduras)
		/// </summary>
		ES_HN = 18442,
		/// <summary>
		/// Spanish (Mexico)
		/// </summary>
		ES_MX = 2058,
		/// <summary>
		/// Spanish (Nicaragua)
		/// </summary>
		ES_NI = 19466,
		/// <summary>
		/// Spanish (Panama)
		/// </summary>
		ES_PA = 6154,
		/// <summary>
		/// Spanish (Peru)
		/// </summary>
		ES_PE = 10250,
		/// <summary>
		/// Spanish (Puerto Rico)
		/// </summary>
		ES_PR = 20490,
		/// <summary>
		/// Spanish (Paraguay)
		/// </summary>
		ES_PY = 15370,
		/// <summary>
		/// Spanish (El Salvador)
		/// </summary>
		ES_SV = 17418,
		/// <summary>
		/// Spanish (United States)
		/// </summary>
		ES_US = 21514,
		/// <summary>
		/// Spanish (Uruguay)
		/// </summary>
		ES_UY = 14346,
		/// <summary>
		/// Spanish (Bolivarian Republic of Venezuela)
		/// </summary>
		ES_VE = 8202,
		/// <summary>
		/// Estonian
		/// </summary>
		ET = 37,
		/// <summary>
		/// Estonian (Estonia)
		/// </summary>
		ET_EE = 1061,
		/// <summary>
		/// Basque
		/// </summary>
		EU = 45,
		/// <summary>
		/// Basque (Basque)
		/// </summary>
		EU_ES = 1069,
		/// <summary>
		/// Persian
		/// </summary>
		FA = 41,
		/// <summary>
		/// Persian
		/// </summary>
		FA_IR = 1065,
		/// <summary>
		/// Fulah
		/// </summary>
		FF = 103,
		/// <summary>
		/// Fulah (Latin)
		/// </summary>
		FF_LATN = 31847,
		/// <summary>
		/// Fulah (Latin, Senegal)
		/// </summary>
		FF_LATN_SN = 2151,
		/// <summary>
		/// Finnish
		/// </summary>
		FI = 11,
		/// <summary>
		/// Finnish (Finland)
		/// </summary>
		FI_FI = 1035,
		/// <summary>
		/// Filipino
		/// </summary>
		FIL = 100,
		/// <summary>
		/// Filipino (Philippines)
		/// </summary>
		FIL_PH = 1124,
		/// <summary>
		/// Faroese
		/// </summary>
		FO = 56,
		/// <summary>
		/// Faroese (Faroe Islands)
		/// </summary>
		FO_FO = 1080,
		/// <summary>
		/// French
		/// </summary>
		FR = 12,
		/// <summary>
		/// French (Belgium)
		/// </summary>
		FR_BE = 2060,
		/// <summary>
		/// French (Canada)
		/// </summary>
		FR_CA = 3084,
		/// <summary>
		/// French (Congo DRC)
		/// </summary>
		FR_CD = 9228,
		/// <summary>
		/// French (Switzerland)
		/// </summary>
		FR_CH = 4108,
		/// <summary>
		/// French (Côte d’Ivoire)
		/// </summary>
		FR_CI = 12300,
		/// <summary>
		/// French (Cameroon)
		/// </summary>
		FR_CM = 11276,
		/// <summary>
		/// French (France)
		/// </summary>
		FR_FR = 1036,
		/// <summary>
		/// French (Haiti)
		/// </summary>
		FR_HT = 15372,
		/// <summary>
		/// French (Luxembourg)
		/// </summary>
		FR_LU = 5132,
		/// <summary>
		/// French (Morocco)
		/// </summary>
		FR_MA = 14348,
		/// <summary>
		/// French (Monaco)
		/// </summary>
		FR_MC = 6156,
		/// <summary>
		/// French (Mali)
		/// </summary>
		FR_ML = 13324,
		/// <summary>
		/// French (Reunion)
		/// </summary>
		FR_RE = 8204,
		/// <summary>
		/// French (Senegal)
		/// </summary>
		FR_SN = 10252,
		/// <summary>
		/// Frisian
		/// </summary>
		FY = 98,
		/// <summary>
		/// Frisian (Netherlands)
		/// </summary>
		FY_NL = 1122,
		/// <summary>
		/// Irish
		/// </summary>
		GA = 60,
		/// <summary>
		/// Irish (Ireland)
		/// </summary>
		GA_IE = 2108,
		/// <summary>
		/// Scottish Gaelic
		/// </summary>
		GD = 145,
		/// <summary>
		/// Scottish Gaelic (United Kingdom)
		/// </summary>
		GD_GB = 1169,
		/// <summary>
		/// Galician
		/// </summary>
		GL = 86,
		/// <summary>
		/// Galician (Galician)
		/// </summary>
		GL_ES = 1110,
		/// <summary>
		/// Guarani
		/// </summary>
		GN = 116,
		/// <summary>
		/// Guarani (Paraguay)
		/// </summary>
		GN_PY = 1140,
		/// <summary>
		/// Alsatian
		/// </summary>
		GSW = 132,
		/// <summary>
		/// Alsatian (France)
		/// </summary>
		GSW_FR = 1156,
		/// <summary>
		/// Gujarati
		/// </summary>
		GU = 71,
		/// <summary>
		/// Gujarati (India)
		/// </summary>
		GU_IN = 1095,
		/// <summary>
		/// Hausa
		/// </summary>
		HA = 104,
		/// <summary>
		/// Hausa (Latin)
		/// </summary>
		HA_LATN = 31848,
		/// <summary>
		/// Hausa (Latin, Nigeria)
		/// </summary>
		HA_LATN_NG = 1128,
		/// <summary>
		/// Hawaiian
		/// </summary>
		HAW = 117,
		/// <summary>
		/// Hawaiian (United States)
		/// </summary>
		HAW_US = 1141,
		/// <summary>
		/// Hebrew
		/// </summary>
		HE = 13,
		/// <summary>
		/// Hebrew (Israel)
		/// </summary>
		HE_IL = 1037,
		/// <summary>
		/// Hindi
		/// </summary>
		HI = 57,
		/// <summary>
		/// Hindi (India)
		/// </summary>
		HI_IN = 1081,
		/// <summary>
		/// Croatian
		/// </summary>
		HR = 26,
		/// <summary>
		/// Croatian (Latin, Bosnia and Herzegovina)
		/// </summary>
		HR_BA = 4122,
		/// <summary>
		/// Croatian (Croatia)
		/// </summary>
		HR_HR = 1050,
		/// <summary>
		/// Upper Sorbian
		/// </summary>
		HSB = 46,
		/// <summary>
		/// Upper Sorbian (Germany)
		/// </summary>
		HSB_DE = 1070,
		/// <summary>
		/// Hungarian
		/// </summary>
		HU = 14,
		/// <summary>
		/// Hungarian (Hungary)
		/// </summary>
		HU_HU = 1038,
		/// <summary>
		/// Armenian
		/// </summary>
		HY = 43,
		/// <summary>
		/// Armenian (Armenia)
		/// </summary>
		HY_AM = 1067,
		/// <summary>
		/// Indonesian
		/// </summary>
		ID = 33,
		/// <summary>
		/// Indonesian (Indonesia)
		/// </summary>
		ID_ID = 1057,
		/// <summary>
		/// Igbo
		/// </summary>
		IG = 112,
		/// <summary>
		/// Igbo (Nigeria)
		/// </summary>
		IG_NG = 1136,
		/// <summary>
		/// Yi
		/// </summary>
		II = 120,
		/// <summary>
		/// Yi (PRC)
		/// </summary>
		II_CN = 1144,
		/// <summary>
		/// Icelandic
		/// </summary>
		IS = 15,
		/// <summary>
		/// Icelandic (Iceland)
		/// </summary>
		IS_IS = 1039,
		/// <summary>
		/// Italian
		/// </summary>
		IT = 16,
		/// <summary>
		/// Italian (Switzerland)
		/// </summary>
		IT_CH = 2064,
		/// <summary>
		/// Italian (Italy)
		/// </summary>
		IT_IT = 1040,
		/// <summary>
		/// Inuktitut
		/// </summary>
		IU = 93,
		/// <summary>
		/// Inuktitut (Syllabics)
		/// </summary>
		IU_CANS = 30813,
		/// <summary>
		/// Inuktitut (Syllabics, Canada)
		/// </summary>
		IU_CANS_CA = 1117,
		/// <summary>
		/// Inuktitut (Latin)
		/// </summary>
		IU_LATN = 31837,
		/// <summary>
		/// Inuktitut (Latin, Canada)
		/// </summary>
		IU_LATN_CA = 2141,
		/// <summary>
		/// Japanese
		/// </summary>
		JA = 17,
		/// <summary>
		/// Japanese (Japan)
		/// </summary>
		JA_JP = 1041,
		/// <summary>
		/// Basa Jawa
		/// </summary>
		JV = 4096,
		/// <summary>
		/// Georgian
		/// </summary>
		KA = 55,
		/// <summary>
		/// Georgian (Georgia)
		/// </summary>
		KA_GE = 1079,
		/// <summary>
		/// Kazakh
		/// </summary>
		KK = 63,
		/// <summary>
		/// Kazakh (Kazakhstan)
		/// </summary>
		KK_KZ = 1087,
		/// <summary>
		/// Greenlandic
		/// </summary>
		KL = 111,
		/// <summary>
		/// Greenlandic (Greenland)
		/// </summary>
		KL_GL = 1135,
		/// <summary>
		/// Khmer
		/// </summary>
		KM = 83,
		/// <summary>
		/// Khmer (Cambodia)
		/// </summary>
		KM_KH = 1107,
		/// <summary>
		/// Kannada
		/// </summary>
		KN = 75,
		/// <summary>
		/// Kannada (India)
		/// </summary>
		KN_IN = 1099,
		/// <summary>
		/// Korean
		/// </summary>
		KO = 18,
		/// <summary>
		/// Korean (Korea)
		/// </summary>
		KO_KR = 1042,
		/// <summary>
		/// Konkani
		/// </summary>
		KOK = 87,
		/// <summary>
		/// Konkani (India)
		/// </summary>
		KOK_IN = 1111,
		/// <summary>
		/// Central Kurdish
		/// </summary>
		KU = 146,
		/// <summary>
		/// Central Kurdish (Arabic)
		/// </summary>
		KU_ARAB = 31890,
		/// <summary>
		/// Central Kurdish (Iraq)
		/// </summary>
		KU_ARAB_IQ = 1170,
		/// <summary>
		/// Kyrgyz
		/// </summary>
		KY = 64,
		/// <summary>
		/// Kyrgyz (Kyrgyzstan)
		/// </summary>
		KY_KG = 1088,
		/// <summary>
		/// Luxembourgish
		/// </summary>
		LB = 110,
		/// <summary>
		/// Luxembourgish (Luxembourg)
		/// </summary>
		LB_LU = 1134,
		/// <summary>
		/// Lao
		/// </summary>
		LO = 84,
		/// <summary>
		/// Lao (Lao P.D.R.)
		/// </summary>
		LO_LA = 1108,
		/// <summary>
		/// Lithuanian
		/// </summary>
		LT = 39,
		/// <summary>
		/// Lithuanian (Lithuania)
		/// </summary>
		LT_LT = 1063,
		/// <summary>
		/// Latvian
		/// </summary>
		LV = 38,
		/// <summary>
		/// Latvian (Latvia)
		/// </summary>
		LV_LV = 1062,
		/// <summary>
		/// Maori
		/// </summary>
		MI = 129,
		/// <summary>
		/// Maori (New Zealand)
		/// </summary>
		MI_NZ = 1153,
		/// <summary>
		/// Macedonian (FYROM)
		/// </summary>
		MK = 47,
		/// <summary>
		/// Macedonian (Former Yugoslav Republic of Macedonia)
		/// </summary>
		MK_MK = 1071,
		/// <summary>
		/// Malayalam
		/// </summary>
		ML = 76,
		/// <summary>
		/// Malayalam (India)
		/// </summary>
		ML_IN = 1100,
		/// <summary>
		/// Mongolian
		/// </summary>
		MN = 80,
		/// <summary>
		/// Mongolian (Cyrillic)
		/// </summary>
		MN_CYRL = 30800,
		/// <summary>
		/// Mongolian (Cyrillic, Mongolia)
		/// </summary>
		MN_MN = 1104,
		/// <summary>
		/// Mongolian (Traditional Mongolian)
		/// </summary>
		MN_MONG = 31824,
		/// <summary>
		/// Mongolian (Traditional Mongolian, PRC)
		/// </summary>
		MN_MONG_CN = 2128,
		/// <summary>
		/// Mongolian (Traditional Mongolian, Mongolia)
		/// </summary>
		MN_MONG_MN = 3152,
		/// <summary>
		/// Mohawk
		/// </summary>
		MOH = 124,
		/// <summary>
		/// Mohawk (Mohawk)
		/// </summary>
		MOH_CA = 1148,
		/// <summary>
		/// Marathi
		/// </summary>
		MR = 78,
		/// <summary>
		/// Marathi (India)
		/// </summary>
		MR_IN = 1102,
		/// <summary>
		/// Malay
		/// </summary>
		MS = 62,
		/// <summary>
		/// Malay (Brunei Darussalam)
		/// </summary>
		MS_BN = 2110,
		/// <summary>
		/// Malay (Malaysia)
		/// </summary>
		MS_MY = 1086,
		/// <summary>
		/// Maltese
		/// </summary>
		MT = 58,
		/// <summary>
		/// Maltese (Malta)
		/// </summary>
		MT_MT = 1082,
		/// <summary>
		/// Burmese
		/// </summary>
		MY = 85,
		/// <summary>
		/// Burmese (Myanmar)
		/// </summary>
		MY_MM = 1109,
		/// <summary>
		/// Norwegian (Bokmål)
		/// </summary>
		NB = 31764,
		/// <summary>
		/// Norwegian, Bokmål (Norway)
		/// </summary>
		NB_NO = 1044,
		/// <summary>
		/// Nepali
		/// </summary>
		NE = 97,
		/// <summary>
		/// Nepali (India)
		/// </summary>
		NE_IN = 2145,
		/// <summary>
		/// Nepali (Nepal)
		/// </summary>
		NE_NP = 1121,
		/// <summary>
		/// Dutch
		/// </summary>
		NL = 19,
		/// <summary>
		/// Dutch (Belgium)
		/// </summary>
		NL_BE = 2067,
		/// <summary>
		/// Dutch (Netherlands)
		/// </summary>
		NL_NL = 1043,
		/// <summary>
		/// Norwegian (Nynorsk)
		/// </summary>
		NN = 30740,
		/// <summary>
		/// Norwegian, Nynorsk (Norway)
		/// </summary>
		NN_NO = 2068,
		/// <summary>
		/// Norwegian
		/// </summary>
		NO = 20,
		/// <summary>
		/// Sesotho sa Leboa
		/// </summary>
		NSO = 108,
		/// <summary>
		/// Sesotho sa Leboa (South Africa)
		/// </summary>
		NSO_ZA = 1132,
		/// <summary>
		/// Occitan
		/// </summary>
		OC = 130,
		/// <summary>
		/// Occitan (France)
		/// </summary>
		OC_FR = 1154,
		/// <summary>
		/// Oromo
		/// </summary>
		OM = 114,
		/// <summary>
		/// Oromo (Ethiopia)
		/// </summary>
		OM_ET = 1138,
		/// <summary>
		/// Odia
		/// </summary>
		OR = 72,
		/// <summary>
		/// Odia (India)
		/// </summary>
		OR_IN = 1096,
		/// <summary>
		/// Punjabi
		/// </summary>
		PA = 70,
		/// <summary>
		/// Punjabi (Arabic)
		/// </summary>
		PA_ARAB = 31814,
		/// <summary>
		/// Punjabi (Islamic Republic of Pakistan)
		/// </summary>
		PA_ARAB_PK = 2118,
		/// <summary>
		/// Punjabi (India)
		/// </summary>
		PA_IN = 1094,
		/// <summary>
		/// Polish
		/// </summary>
		PL = 21,
		/// <summary>
		/// Polish (Poland)
		/// </summary>
		PL_PL = 1045,
		/// <summary>
		/// Dari
		/// </summary>
		PRS = 140,
		/// <summary>
		/// Dari (Afghanistan)
		/// </summary>
		PRS_AF = 1164,
		/// <summary>
		/// Pashto
		/// </summary>
		PS = 99,
		/// <summary>
		/// Pashto (Afghanistan)
		/// </summary>
		PS_AF = 1123,
		/// <summary>
		/// Portuguese
		/// </summary>
		PT = 22,
		/// <summary>
		/// Portuguese (Brazil)
		/// </summary>
		PT_BR = 1046,
		/// <summary>
		/// Portuguese (Portugal)
		/// </summary>
		PT_PT = 2070,
		/// <summary>
		/// K'iche
		/// </summary>
		QUT = 134,
		/// <summary>
		/// K'iche (Guatemala)
		/// </summary>
		QUT_GT = 1158,
		/// <summary>
		/// Quechua
		/// </summary>
		QUZ = 107,
		/// <summary>
		/// Quechua (Bolivia)
		/// </summary>
		QUZ_BO = 1131,
		/// <summary>
		/// Quechua (Ecuador)
		/// </summary>
		QUZ_EC = 2155,
		/// <summary>
		/// Quechua (Peru)
		/// </summary>
		QUZ_PE = 3179,
		/// <summary>
		/// Romansh
		/// </summary>
		RM = 23,
		/// <summary>
		/// Romansh (Switzerland)
		/// </summary>
		RM_CH = 1047,
		/// <summary>
		/// Romanian
		/// </summary>
		RO = 24,
		/// <summary>
		/// Romanian (Moldova)
		/// </summary>
		RO_MD = 2072,
		/// <summary>
		/// Romanian (Romania)
		/// </summary>
		RO_RO = 1048,
		/// <summary>
		/// Russian
		/// </summary>
		RU = 25,
		/// <summary>
		/// Russian (Russia)
		/// </summary>
		RU_RU = 1049,
		/// <summary>
		/// Kinyarwanda
		/// </summary>
		RW = 135,
		/// <summary>
		/// Kinyarwanda (Rwanda)
		/// </summary>
		RW_RW = 1159,
		/// <summary>
		/// Sanskrit
		/// </summary>
		SA = 79,
		/// <summary>
		/// Sanskrit (India)
		/// </summary>
		SA_IN = 1103,
		/// <summary>
		/// Sakha
		/// </summary>
		SAH = 133,
		/// <summary>
		/// Sakha (Russia)
		/// </summary>
		SAH_RU = 1157,
		/// <summary>
		/// Sindhi
		/// </summary>
		SD = 89,
		/// <summary>
		/// Sindhi (Arabic)
		/// </summary>
		SD_ARAB = 31833,
		/// <summary>
		/// Sindhi (Islamic Republic of Pakistan)
		/// </summary>
		SD_ARAB_PK = 2137,
		/// <summary>
		/// Sami (Northern)
		/// </summary>
		SE = 59,
		/// <summary>
		/// Sami, Northern (Finland)
		/// </summary>
		SE_FI = 3131,
		/// <summary>
		/// Sami, Northern (Norway)
		/// </summary>
		SE_NO = 1083,
		/// <summary>
		/// Sami, Northern (Sweden)
		/// </summary>
		SE_SE = 2107,
		/// <summary>
		/// Sinhala
		/// </summary>
		SI = 91,
		/// <summary>
		/// Sinhala (Sri Lanka)
		/// </summary>
		SI_LK = 1115,
		/// <summary>
		/// Slovak
		/// </summary>
		SK = 27,
		/// <summary>
		/// Slovak (Slovakia)
		/// </summary>
		SK_SK = 1051,
		/// <summary>
		/// Slovenian
		/// </summary>
		SL = 36,
		/// <summary>
		/// Slovenian (Slovenia)
		/// </summary>
		SL_SI = 1060,
		/// <summary>
		/// Sami (Southern)
		/// </summary>
		SMA = 30779,
		/// <summary>
		/// Sami, Southern (Norway)
		/// </summary>
		SMA_NO = 6203,
		/// <summary>
		/// Sami, Southern (Sweden)
		/// </summary>
		SMA_SE = 7227,
		/// <summary>
		/// Sami (Lule)
		/// </summary>
		SMJ = 31803,
		/// <summary>
		/// Sami, Lule (Norway)
		/// </summary>
		SMJ_NO = 4155,
		/// <summary>
		/// Sami, Lule (Sweden)
		/// </summary>
		SMJ_SE = 5179,
		/// <summary>
		/// Sami (Inari)
		/// </summary>
		SMN = 28731,
		/// <summary>
		/// Sami, Inari (Finland)
		/// </summary>
		SMN_FI = 9275,
		/// <summary>
		/// Sami (Skolt)
		/// </summary>
		SMS = 29755,
		/// <summary>
		/// Sami, Skolt (Finland)
		/// </summary>
		SMS_FI = 8251,
		/// <summary>
		/// Somali
		/// </summary>
		SO = 119,
		/// <summary>
		/// Somali (Somalia)
		/// </summary>
		SO_SO = 1143,
		/// <summary>
		/// Albanian
		/// </summary>
		SQ = 28,
		/// <summary>
		/// Albanian (Albania)
		/// </summary>
		SQ_AL = 1052,
		/// <summary>
		/// Serbian
		/// </summary>
		SR = 31770,
		/// <summary>
		/// Serbian (Cyrillic)
		/// </summary>
		SR_CYRL = 27674,
		/// <summary>
		/// Serbian (Cyrillic, Bosnia and Herzegovina)
		/// </summary>
		SR_CYRL_BA = 7194,
		/// <summary>
		/// Serbian (Cyrillic, Serbia and Montenegro (Former))
		/// </summary>
		SR_CYRL_CS = 3098,
		/// <summary>
		/// Serbian (Cyrillic, Montenegro)
		/// </summary>
		SR_CYRL_ME = 12314,
		/// <summary>
		/// Serbian (Cyrillic, Serbia)
		/// </summary>
		SR_CYRL_RS = 10266,
		/// <summary>
		/// Serbian (Latin)
		/// </summary>
		SR_LATN = 28698,
		/// <summary>
		/// Serbian (Latin, Bosnia and Herzegovina)
		/// </summary>
		SR_LATN_BA = 6170,
		/// <summary>
		/// Serbian (Latin, Serbia and Montenegro (Former))
		/// </summary>
		SR_LATN_CS = 2074,
		/// <summary>
		/// Serbian (Latin, Montenegro)
		/// </summary>
		SR_LATN_ME = 11290,
		/// <summary>
		/// Serbian (Latin, Serbia)
		/// </summary>
		SR_LATN_RS = 9242,
		/// <summary>
		/// Southern Sotho
		/// </summary>
		ST = 48,
		/// <summary>
		/// Southern Sotho (South Africa)
		/// </summary>
		ST_ZA = 1072,
		/// <summary>
		/// Swedish
		/// </summary>
		SV = 29,
		/// <summary>
		/// Swedish (Finland)
		/// </summary>
		SV_FI = 2077,
		/// <summary>
		/// Swedish (Sweden)
		/// </summary>
		SV_SE = 1053,
		/// <summary>
		/// Kiswahili
		/// </summary>
		SW = 65,
		/// <summary>
		/// Kiswahili (Kenya)
		/// </summary>
		SW_KE = 1089,
		/// <summary>
		/// Syriac
		/// </summary>
		SYR = 90,
		/// <summary>
		/// Syriac (Syria)
		/// </summary>
		SYR_SY = 1114,
		/// <summary>
		/// Tamil
		/// </summary>
		TA = 73,
		/// <summary>
		/// Tamil (India)
		/// </summary>
		TA_IN = 1097,
		/// <summary>
		/// Tamil (Sri Lanka)
		/// </summary>
		TA_LK = 2121,
		/// <summary>
		/// Telugu
		/// </summary>
		TE = 74,
		/// <summary>
		/// Telugu (India)
		/// </summary>
		TE_IN = 1098,
		/// <summary>
		/// Tajik
		/// </summary>
		TG = 40,
		/// <summary>
		/// Tajik (Cyrillic)
		/// </summary>
		TG_CYRL = 31784,
		/// <summary>
		/// Tajik (Cyrillic, Tajikistan)
		/// </summary>
		TG_CYRL_TJ = 1064,
		/// <summary>
		/// Thai
		/// </summary>
		TH = 30,
		/// <summary>
		/// Thai (Thailand)
		/// </summary>
		TH_TH = 1054,
		/// <summary>
		/// Tigrinya
		/// </summary>
		TI = 115,
		/// <summary>
		/// Tigrinya (Eritrea)
		/// </summary>
		TI_ER = 2163,
		/// <summary>
		/// Tigrinya (Ethiopia)
		/// </summary>
		TI_ET = 1139,
		/// <summary>
		/// Turkmen
		/// </summary>
		TK = 66,
		/// <summary>
		/// Turkmen (Turkmenistan)
		/// </summary>
		TK_TM = 1090,
		/// <summary>
		/// Setswana
		/// </summary>
		TN = 50,
		/// <summary>
		/// Setswana (Botswana)
		/// </summary>
		TN_BW = 2098,
		/// <summary>
		/// Setswana (South Africa)
		/// </summary>
		TN_ZA = 1074,
		/// <summary>
		/// Turkish
		/// </summary>
		TR = 31,
		/// <summary>
		/// Turkish (Turkey)
		/// </summary>
		TR_TR = 1055,
		/// <summary>
		/// Tsonga
		/// </summary>
		TS = 49,
		/// <summary>
		/// Tsonga (South Africa)
		/// </summary>
		TS_ZA = 1073,
		/// <summary>
		/// Tatar
		/// </summary>
		TT = 68,
		/// <summary>
		/// Tatar (Russia)
		/// </summary>
		TT_RU = 1092,
		/// <summary>
		/// Tamazight
		/// </summary>
		TZM = 95,
		/// <summary>
		/// Tamazight (Latin)
		/// </summary>
		TZM_LATN = 31839,
		/// <summary>
		/// Tamazight (Latin, Algeria)
		/// </summary>
		TZM_LATN_DZ = 2143,
		/// <summary>
		/// Tamazight (Tifinagh)
		/// </summary>
		TZM_TFNG = 30815,
		/// <summary>
		/// Central Atlas Tamazight (Tifinagh, Morocco)
		/// </summary>
		TZM_TFNG_MA = 4191,
		/// <summary>
		/// Uyghur
		/// </summary>
		UG = 128,
		/// <summary>
		/// Uyghur (PRC)
		/// </summary>
		UG_CN = 1152,
		/// <summary>
		/// Ukrainian
		/// </summary>
		UK = 34,
		/// <summary>
		/// Ukrainian (Ukraine)
		/// </summary>
		UK_UA = 1058,
		/// <summary>
		/// Urdu
		/// </summary>
		UR = 32,
		/// <summary>
		/// Urdu (India)
		/// </summary>
		UR_IN = 2080,
		/// <summary>
		/// Urdu (Islamic Republic of Pakistan)
		/// </summary>
		UR_PK = 1056,
		/// <summary>
		/// Uzbek
		/// </summary>
		UZ = 67,
		/// <summary>
		/// Uzbek (Cyrillic)
		/// </summary>
		UZ_CYRL = 30787,
		/// <summary>
		/// Uzbek (Cyrillic, Uzbekistan)
		/// </summary>
		UZ_CYRL_UZ = 2115,
		/// <summary>
		/// Uzbek (Latin)
		/// </summary>
		UZ_LATN = 31811,
		/// <summary>
		/// Uzbek (Latin, Uzbekistan)
		/// </summary>
		UZ_LATN_UZ = 1091,
		/// <summary>
		/// Vietnamese
		/// </summary>
		VI = 42,
		/// <summary>
		/// Vietnamese (Vietnam)
		/// </summary>
		VI_VN = 1066,
		/// <summary>
		/// Wolof
		/// </summary>
		WO = 136,
		/// <summary>
		/// Wolof (Senegal)
		/// </summary>
		WO_SN = 1160,
		/// <summary>
		/// isiXhosa
		/// </summary>
		XH = 52,
		/// <summary>
		/// isiXhosa (South Africa)
		/// </summary>
		XH_ZA = 1076,
		/// <summary>
		/// Yoruba
		/// </summary>
		YO = 106,
		/// <summary>
		/// Yoruba (Nigeria)
		/// </summary>
		YO_NG = 1130,
		/// <summary>
		/// Chinese
		/// </summary>
		ZH = 30724,
		/// <summary>
		/// Chinese (Simplified, PRC)
		/// </summary>
		ZH_CN = 2052,
		/// <summary>
		/// Chinese (Simplified) Legacy
		/// </summary>
		ZH_CHS = 4,
		/// <summary>
		/// Chinese (Traditional) Legacy
		/// </summary>
		ZH_CHT = 31748,
		/// <summary>
		/// Chinese (Traditional, Hong Kong S.A.R.)
		/// </summary>
		ZH_HK = 3076,
		/// <summary>
		/// Chinese (Traditional, Macao S.A.R.)
		/// </summary>
		ZH_MO = 5124,
		/// <summary>
		/// Chinese (Simplified, Singapore)
		/// </summary>
		ZH_SG = 4100,
		/// <summary>
		/// Chinese (Traditional, Taiwan)
		/// </summary>
		ZH_TW = 1028,
		/// <summary>
		/// isiZulu
		/// </summary>
		ZU = 53,
		/// <summary>
		/// isiZulu (South Africa)
		/// </summary>
		ZU_ZA = 1077
	}
}